name: Build

# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      # choose your default branch
      - master
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          path: "src"

      - name: Checkout builds
        uses: actions/checkout@v4.2.2
        with:
          ref: "builds"
          path: "builds"

      - name: Clean old builds
        run: |
          rm $GITHUB_WORKSPACE/builds/*.cs3 || true
          rm $GITHUB_WORKSPACE/builds/*.jar || true

      - name: Setup JDK 17
        uses: actions/setup-java@v4.6.0
        with:
          distribution: "adopt"
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.2

      - name: Access Secrets
        env:
          TMDB_API: ${{ secrets.TMDB_API }}
          DUMP_API: ${{ secrets.DUMP_API }}
          DUMP_KEY: ${{ secrets.DUMP_KEY }}
          ANICHI_API: ${{ secrets.ANICHI_API }}
          ANICHI_SERVER: ${{ secrets.ANICHI_SERVER }}
          ANICHI_ENDPOINT: ${{ secrets.ANICHI_ENDPOINT }}
          ANICHI_APP: ${{ secrets.ANICHI_APP }}
          ZSHOW_API: ${{ secrets.ZSHOW_API }}
          SFMOVIES_API: ${{ secrets.SFMOVIES_API }}
          CINEMATV_API: ${{ secrets.CINEMATV_API }}
          GHOSTX_API: ${{ secrets.GHOSTX_API }}
          SUPERSTREAM_FIRST_API: ${{ secrets.SUPERSTREAM_FIRST_API }}
          SUPERSTREAM_SECOND_API: ${{ secrets.SUPERSTREAM_SECOND_API }}
          SUPERSTREAM_THIRD_API: ${{ secrets.SUPERSTREAM_THIRD_API }}
          SUPERSTREAM_FOURTH_API: ${{ secrets.SUPERSTREAM_FOURTH_API }}
          AsianDrama_API: ${{ secrets.AsianDrama_API }}
          FanCode_API: ${{ secrets.FanCode_API }}
          Whvx_API: ${{ secrets.Whvx_API }}
          JapanIPTV: ${{ secrets.JapanIPTV }}
          SonyIPTV: ${{ secrets.SonyIPTV }}
          PirateIPTV: ${{ secrets.PirateIPTV }}
          Su_sports: ${{ secrets.Su_sports }}
          CatflixAPI: ${{ secrets.CatflixAPI }}
          ConsumetAPI: ${{ secrets.ConsumetAPI }}
          FlixHQAPI: ${{ secrets.FlixHQAPI }}
          WhvxAPI: ${{ secrets.WhvxAPI }}
          WhvxT: ${{ secrets.WhvxT }}
          SharmaflixApikey: ${{ secrets.SharmaflixApikey }}
          SharmaflixApi: ${{ secrets.SharmaflixApi }}
          Theyallsayflix: ${{ secrets.Theyallsayflix }}
          HianimeAPI: ${{ secrets.HianimeAPI }}
          Vidsrccc: ${{ secrets.Vidsrccc }}
          WASMAPI: ${{ secrets.WASMAPI }}
          KissKh: ${{ secrets.KissKh }}
          KisskhSub: ${{ secrets.KisskhSub }}
          StreamPlayAPI: ${{ secrets.StreamPlayAPI }}
          PROXYAPI: ${{ secrets.PROXYAPI }}
          KAISVA: ${{ secrets.KAISVA }}
          MAL_API: ${{ secrets.MAL_API }}
          MOVIEBOX_SECRET_KEY_ALT: ${{ secrets.MOVIEBOX_SECRET_KEY_ALT }}
          MOVIEBOX_SECRET_KEY_DEFAULT: ${{ secrets.MOVIEBOX_SECRET_KEY_DEFAULT }}
          SuperToken: ${{ secrets.SuperToken }}
        run: |
          cd $GITHUB_WORKSPACE/src
          echo TMDB_API=$TMDB_API >> local.properties
          echo DUMP_API=$DUMP_API >> local.properties
          echo DUMP_KEY=$DUMP_KEY >> local.properties
          echo ANICHI_API=$ANICHI_API >> local.properties
          echo ANICHI_SERVER=$ANICHI_SERVER >> local.properties
          echo ANICHI_ENDPOINT=$ANICHI_ENDPOINT >> local.properties
          echo ANICHI_APP=$ANICHI_APP >> local.properties
          echo ZSHOW_API=$ZSHOW_API >> local.properties
          echo SFMOVIES_API=$SFMOVIES_API >> local.properties
          echo CINEMATV_API=$CINEMATV_API >> local.properties
          echo GHOSTX_API=$GHOSTX_API >> local.properties
          echo SUPERSTREAM_FIRST_API=$SUPERSTREAM_FIRST_API >> local.properties
          echo SUPERSTREAM_SECOND_API=$SUPERSTREAM_SECOND_API >> local.properties
          echo SUPERSTREAM_THIRD_API=$SUPERSTREAM_THIRD_API >> local.properties
          echo SUPERSTREAM_FOURTH_API=$SUPERSTREAM_FOURTH_API >> local.properties
          echo AsianDrama_API=$AsianDrama_API >> local.properties
          echo FanCode_API=$FanCode_API >> local.properties
          echo Whvx_API=$Whvx_API >> local.properties
          echo Su_sports=$Su_sports >> local.properties
          echo PirateIPTV=$PirateIPTV >> local.properties
          echo SonyIPTV=$SonyIPTV >> local.properties
          echo JapanIPTV=$JapanIPTV >> local.properties
          echo CatflixAPI=$CatflixAPI >> local.properties
          echo ConsumetAPI=$ConsumetAPI >> local.properties
          echo FlixHQAPI=$FlixHQAPI >> local.properties
          echo WhvxAPI=$WhvxAPI >> local.properties
          echo WhvxT=$WhvxT >> local.properties
          echo SharmaflixApi=$SharmaflixApi >> local.properties
          echo SharmaflixApikey=$SharmaflixApikey >> local.properties
          echo HianimeAPI=$HianimeAPI >> local.properties
          echo Vidsrccc=$Vidsrccc >> local.properties
          echo WASMAPI=$WASMAPI >> local.properties
          echo KissKh=$KissKh >> local.properties
          echo KisskhSub=$KisskhSub >> local.properties
          echo StreamPlayAPI=$StreamPlayAPI >> local.properties
          echo PROXYAPI=$PROXYAPI >> local.properties
          echo KAISVA=$KAISVA >> local.properties
          echo MAL_API=$MAL_API >> local.properties
          echo MOVIEBOX_SECRET_KEY_DEFAULT=$MOVIEBOX_SECRET_KEY_DEFAULT >> local.properties
          echo MOVIEBOX_SECRET_KEY_ALT=$MOVIEBOX_SECRET_KEY_ALT >> local.properties
          echo SuperToken=$SuperToken >> local.properties
      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson
          ./gradlew ensureJarCompatibility
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds
          cp **/build/*.jar $GITHUB_WORKSPACE/builds
          cp build/plugins.json $GITHUB_WORKSPACE/builds

      - name: Push builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit --amend -m "Build $GITHUB_SHA" || exit 0   # do not error if nothing to commit
          git push --force
